// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "etop/templates/components/ui"

// NotFound Page
func NotFound() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\" x-data=\"{ pageTitle: '404 Page Not Found - etop' }\" x-init=\"document.title = pageTitle; $watch('pageTitle', value => document.title = value);\"><div><h2 class=\"text-3xl font-bold tracking-tight\">Oops!</h2><p class=\"text-muted-foreground\">Sorry, the page you are looking for could not be found.</p></div><!-- Action --><div class=\"text-card-foreground p-6\"><div class=\"flex flex-col items-center justify-start\"><!-- Big Oops --><h1 class=\"galaxy-text font-extrabold mb-4 text-8xl sm:text-[96px] lg:text-[120px] leading-none tracking-tight dark:opacity-50\">404</h1><!-- Subtitle --><p class=\"text-gray-500 max-w-md text-center mb-6\">The page you are looking for might have been removed,<br>had its name changed, or is temporarily unavailable.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Button("back-dasboard", "outline", "", "", "Back to Dashboard", "",
			templ.Attributes{"type": "button", "hx-post": "/", "hx-target": "#content", "hx-swap": "innerHTML", "hx-push-url": "true"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
