// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AuthLayout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>etop</title><link rel=\"stylesheet\" href=\"/public/css/styles.css\"><script src=\"/public/js/htmx.min.js\"></script><script src=\"/public/js/cdn.min.js\" defer></script><script src=\"/public/js/lucide.js\"></script></head><body class=\"min-h-screen bg-background text-foreground\" x-data=\"{ \r\n\t\t\t\tsidebarOpen: false, \r\n\t\t\t\tsidebarCollapsed: false, \r\n\t\t\t\tdarkMode: localStorage.getItem(&#39;darkMode&#39;) === &#39;true&#39; || false,\r\n\t\t\t\tisMobile: window.innerWidth &lt; 768\r\n\t\t\t}\" x-init=\"\r\n\t\t\t\t$watch(&#39;darkMode&#39;, val =&gt; {\r\n\t\t\t\t\tlocalStorage.setItem(&#39;darkMode&#39;, val);\r\n\t\t\t\t\tif (val) {\r\n\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t\t\tif (darkMode) {\r\n\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\r\n\t\t\t\t}\r\n\t\t\t\twindow.addEventListener(&#39;resize&#39;, () =&gt; {\r\n\t\t\t\t\tisMobile = window.innerWidth &lt; 768;\r\n\t\t\t\t\tif (!isMobile) sidebarOpen = false;\r\n\t\t\t\t});\r\n\t\t\t\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
