// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"os"
	"strings"

	"etop/dto"
	"etop/services"
	"etop/templates/components"
	"etop/templates/features"
	"etop/utils"
)

// Base Layout
func Layout(title string, user dto.UserAuth, content ...templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 22, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(os.Getenv("APP_NAME"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 22, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title><link rel=\"icon\" href=\"data:,\"><link rel=\"stylesheet\" href=\"/public/css/styles.css\"><script src=\"/public/js/htmx.min.js\"></script><script src=\"/public/js/cdn.min.js\" defer></script><script src=\"/public/js/lucide.js\"></script><style>\r\n\t\t\t\t\r\n\t\t\t</style></head><body class=\"min-h-screen bg-background text-foreground\" :class=\"darkMode ? &#39;dark&#39; : &#39;&#39;\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("{ auth_id: '%s', full_name: '%s', sidebarOpen: false, sidebarCollapsed: false, darkMode: (localStorage.getItem('darkMode') === 'true' ? true : false), isMobile: window.innerWidth < 768, colorOptions: %s, task_priorities: %s, project_statuses: %s, task_statutes: %s, }", strings.Trim(user.ID, " "), user.FullName, string(utils.MustJSON(services.GetColorOptions())), string(utils.MustJSON(services.GetTaskPriorities())), string(utils.MustJSON(services.GetProjectStatuses())), string(utils.MustJSON(services.GetTaskStatuses()))))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 36, Col: 548}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" x-init=\"\r\n\t\t\t\t$watch(&#39;darkMode&#39;, val =&gt; {\r\n\t\t\t\t\tlocalStorage.setItem(&#39;darkMode&#39;, val);\r\n\t\t\t\t\tif (val) {\r\n\t\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\tdocument.documentElement.classList.remove(&#39;dark&#39;);\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t\t\tif (darkMode) {\r\n\t\t\t\t\tdocument.documentElement.classList.add(&#39;dark&#39;);\r\n\t\t\t\t}\r\n\t\t\t\twindow.addEventListener(&#39;resize&#39;, () =&gt; {\r\n\t\t\t\t\tlet currentSize = isMobile;\r\n\t\t\t\t\tisMobile = window.innerWidth &lt; 768;\r\n\t\t\t\t\tif (!isMobile) sidebarOpen = false;\r\n\t\t\t\t\t\r\n\t\t\t\t\tif (currentSize != isMobile) {\r\n\t\t\t\t\t\thtmx.ajax(&#39;GET&#39;, &#39;/workspace-switcher&#39;, {target: &#39;#workspace-switcher&#39;, swap: &#39;innerHTML&#39;, indicators: []})\r\n\t\t\t\t\t}\r\n\t\t\t\t\t\r\n\t\t\t\t});\r\n\t\t\t\"><div class=\"flex h-screen\"><!-- Desktop Sidebar --><div class=\"hidden md:flex flex-col bg-card border-r border-border transition-all duration-300 ease-in-out\" :class=\"sidebarCollapsed ? &#39;w-16&#39; : &#39;w-64&#39;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Sidebar(false).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><!-- Main Content --><div class=\"flex-1 flex flex-col min-w-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header(user).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- Page Content --><main class=\"flex-1 p-6 overflow-y-auto\"><div id=\"content\" class=\"w-full h-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, c := range content {
			templ_7745c5c3_Err = c.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></main></div><!-- Mobile Sidebar Overlay --><div x-show=\"sidebarOpen &amp;&amp; isMobile\" x-transition:enter=\"transition-opacity ease-linear duration-300\" x-transition:enter-start=\"opacity-0\" x-transition:enter-end=\"opacity-100\" x-transition:leave=\"transition-opacity ease-linear duration-300\" x-transition:leave-start=\"opacity-100\" x-transition:leave-end=\"opacity-0\" class=\"fixed inset-0 z-40 bg-black bg-opacity-50 md:hidden\" @click=\"sidebarOpen = false\"></div><!-- Mobile Sidebar --><div x-show=\"sidebarOpen &amp;&amp; isMobile\" x-transition:enter=\"transition ease-in-out duration-300 transform\" x-transition:enter-start=\"-translate-x-full\" x-transition:enter-end=\"translate-x-0\" x-transition:leave=\"transition ease-in-out duration-300 transform\" x-transition:leave-start=\"translate-x-0\" x-transition:leave-end=\"-translate-x-full\" class=\"fixed inset-y-0 left-0 z-50 w-64 bg-card border-r border-border md:hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Sidebar(true).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Loader("loader").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = features.CreateWorkspace("w-96", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = BaseScript(os.Getenv("APP_NAME")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div id=\"toaster\"></div><script>\r\n\t\t\t\tfunction workspaceSwitcher(defaultWs) {\r\n\t\t\t\t\treturn {\r\n\t\t\t\t\t\topenSelect: false,\r\n\t\t\t\t\t\tselected: { value: \"\", label: \"\", color: \"\" },\r\n\t\t\t\t\t\tinit() {\r\n\t\t\t\t\t\t\t// initial\r\n\t\t\t\t\t\t\tthis.loadFromStorage(defaultWs);\r\n\r\n\t\t\t\t\t\t\t// listen kalau ada perubahan dari luar (tab lain / script lain)\r\n\t\t\t\t\t\t\twindow.addEventListener(\"storage\", (e) => {\r\n\t\t\t\t\t\t\t\tif (e.key === \"currentWorkspace\") {\r\n\t\t\t\t\t\t\t\t\tthis.loadFromStorage(defaultWs);\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t},\r\n\t\t\t\t\t\tloadFromStorage(fallback) {\r\n\t\t\t\t\t\t\tlet saved = localStorage.getItem(\"currentWorkspace\");\r\n\t\t\t\t\t\t\tif (saved) {\r\n\t\t\t\t\t\t\t\ttry { this.selected = JSON.parse(saved); } \r\n\t\t\t\t\t\t\t\tcatch(e) { this.selected = fallback; }\r\n\t\t\t\t\t\t\t} else {\r\n\t\t\t\t\t\t\t\tthis.selected = fallback;\r\n\t\t\t\t\t\t\t\tlocalStorage.setItem(\"currentWorkspace\", JSON.stringify(fallback));\r\n\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t},\r\n\t\t\t\t\t\tselectWorkspace(ws) {\r\n\t\t\t\t\t\t\tthis.selected = ws;\r\n\t\t\t\t\t\t\tlocalStorage.setItem(\"currentWorkspace\", JSON.stringify(ws));\r\n\t\t\t\t\t\t\tthis.openSelect = false;\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\tlucide.createIcons();\r\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func BaseScript(appName string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_BaseScript_ea36`,
		Function: `function __templ_BaseScript_ea36(appName){document.addEventListener("DOMContentLoaded", () => {
		lucide.createIcons();
	});

	// or htmx:afterSwap
	document.body.addEventListener("htmx:afterOnLoad", (e) => {
		if (e.detail.target.id === "content") {
			const newTitle = document.querySelector("#content [data-title]")?.dataset.title;
			if (newTitle) document.title = newTitle !== "" ? newTitle+" - "+appName : appName;
		}
		
		if (e.detail.target.id === "toaster") {
			document.querySelector("#toaster")
				.insertAdjacentHTML("beforeend", e.detail.xhr.responseText);						
		}
		lucide.createIcons();
	});

	document.body.addEventListener("htmx:afterOnLoad", (e) => {
		if (e.detail.target.id === "toaster") {
			document.querySelector("#toaster")
				.insertAdjacentHTML("beforeend", e.detail.xhr.responseText);						
		}
		lucide.createIcons();
	});
	
	document.body.addEventListener("htmx:responseError", function(e) {
		if (e.detail.target.id === "content") {
			document.querySelector("#toaster")
				.insertAdjacentHTML("beforeend", e.detail.xhr.responseText);
		}
	});

	document.addEventListener("alpine:init", () => {
		Alpine.store("dropdown", {
			openId: null,
			isOpen(id) { return this.openId === id },
			toggle(id) { this.openId = this.openId === id ? null : id },
			close() { this.openId = null }
		});
		Alpine.store("modal", {
			active: null,
			open(id) {
				this.active = id
				document.body.classList.add("overflow-hidden")
				document.body.dispatchEvent(new CustomEvent("modal:opened", {
					detail: { id }
				}))
			},
			close(id) {
				if (this.active === id) {
					this.active = null
					document.body.classList.remove("overflow-hidden")
					// Emit event global agar listener lain bisa reset form
					document.body.dispatchEvent(new CustomEvent("modal:closed", {
						detail: { id }
					}))
				}
			},
			isOpen(id) {
				return this.active === id
			}
		});
		Alpine.store("workspace", {
			current: localStorage.getItem("workspace") || "",
			set(val) {
				this.current = val
				localStorage.setItem("workspace", val)
			}
		});
		Alpine.store("navigation", {
			currentPath: window.location.pathname,
			setPath(path) {
				this.currentPath = path
			}
		})

		// Update kalau user pakai tombol back/forward
		window.addEventListener("popstate", () => {
			Alpine.store("navigation").setPath(window.location.pathname)
		})

		// Update kalau htmx ganti url
		document.body.addEventListener("htmx:afterSwap", (e) => {
			if (e.detail.target.id === "content") {
				Alpine.store("navigation").setPath(window.location.pathname)
			}
		})
	});
}`,
		Call:       templ.SafeScript(`__templ_BaseScript_ea36`, appName),
		CallInline: templ.SafeScriptInline(`__templ_BaseScript_ea36`, appName),
	}
}

var _ = templruntime.GeneratedTemplate
