// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ()

func TagInput(id string, name string, placeholder string, initialTags []string, class string, attrs templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"tag-input\" class=\"w-full max-w-md\"><div class=\"flex flex-wrap gap-2 border rounded-md p-2\" id=\"tag-container\"><!-- Tags ditambahkan lewat JS --><input id=\"tag-input-field\" placeholder=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(placeholder)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tag-input.templ`, Line: 12, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"flex-1 px-2 py-1 text-sm border-none bg-transparent placeholder:text-muted-foreground outline-none \"></div><!-- Hidden input untuk submit ke backend --><input id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(id)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tag-input.templ`, Line: 18, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" name=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/tag-input.templ`, Line: 18, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" type=\"hidden\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TagScript(id, initialTags).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func TagScript(id string, initialTags []string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_TagScript_a969`,
		Function: `function __templ_TagScript_a969(id, initialTags){(function () {
        let tags = []; 
        const Id = id;
        tags= initialTags;
        const tagContainer = document.getElementById("tag-container");
        const inputField = document.getElementById("tag-input-field");
        const hiddenTags = document.getElementById(Id);

        function renderTags() {
            // hapus semua span dulu (kecuali input field)
            tagContainer.querySelectorAll("span").forEach(span => span.remove());

            tags.forEach((tag, index) => {
                const span = document.createElement("span");
                span.className = "flex items-center gap-1 bg-green-100 text-green-800 text-sm px-2 py-1 rounded-full";

                const button = document.createElement("button");
                button.type = "button";
                button.innerText = "×";
                button.className = "focus:outline-none";
                button.onclick = () => {
                    tags.splice(index, 1);
                    renderTags();
                };

                const text = document.createElement("span");
                text.innerText = tag;

                span.appendChild(text);
                span.appendChild(button);
                tagContainer.insertBefore(span, inputField);
            });

            hiddenTags.value = JSON.stringify(tags);
        }

        inputField.addEventListener("keydown", function (e) {
            const newTag = inputField.value.trim();
            if (e.key === "Enter") {
                e.preventDefault();
                if (newTag !== "" && !tags.includes(newTag)) {
                    tags.push(newTag);
                    inputField.value = "";
                    renderTags();
                }
            }
            if (e.key === ',') { 
                e.preventDefault();
                if (newTag !== "" && !tags.includes(newTag)) {
                    tags.push(newTag);
                    inputField.value = "";
                    renderTags();
                } else {
                    inputField.value = "";
                }
            }
        });

        inputField.addEventListener("blur", function() {
            const newTag = inputField.value.trim();
            if (newTag !== "" && !tags.includes(newTag)) {
                tags.push(newTag);
                inputField.value = "";
                renderTags();
            } else {
                inputField.value = "";
            }
        });

        // initial render
        if (initialTags.length > 0) {
            renderTags();
        }
    })();
}`,
		Call:       templ.SafeScript(`__templ_TagScript_a969`, id, initialTags),
		CallInline: templ.SafeScriptInline(`__templ_TagScript_a969`, id, initialTags),
	}
}

var _ = templruntime.GeneratedTemplate
